### ISSUE TITLE
Wait ...

### ISSUE THREAD

**Issue by imrenagi** [Midtrans/midtrans-go#4]
Dear maintainer,

In the future, when you think that this project designs and patterns are not the best and easiest to maintain anymore as you mentioned on [veritrans/go-midtrans](https://github.com/veritrans/go-midtrans), please don't create new project. Use git tag instead. haha 🤞🏼 

Good job for the improvement on this API. Seems better indeed. 👏🏼

**Comment by rizdaprasetya** [comment]
Hi mas @imrenagi thanks! yes, perfectly valid. We do agree!
This will be maintained long term and we'll try to properly use tag/versioning, instead of major migration to new project like the last time. Last time was a major changes, bit messy, and we wanted to centralize to from `veritrans` to `Midtrans` github org (and branding), etc. So we decide to create a new fresh one., which will be the last time we should do that.

Thanks for letting us know your concern! 🙂
