### ISSUE TITLE
Error response body for create payout and approve payout different

### ISSUE THREAD

**Issue by richardreynaldo** [Midtrans/midtrans-go#5]
![image](https://user-images.githubusercontent.com/60066897/131818878-f47d8d0c-3a82-46c6-b54c-94237d976e0b.png)

![image](https://user-images.githubusercontent.com/60066897/131818933-995d6ed3-a1ea-4c57-9efc-0e5680c25e76.png)

resulting in error in unmarshal json when getting the error response body

**Comment by Xaxxis** [comment]
Hi @richardreynaldo it's expected to create and approve payout has a different payload. You can find the detail docs from i[ris API documentation](https://docs.midtrans.com/en/technical-reference/postman-collection?id=midtrans-iris-api-postman-collection)

Based on those error screenshots, happened cause you don't send beneficiary_name in create payout request. this is a mandatory field. The minimum request for the body should be like this
`{
    "payouts": [
        {
            "beneficiary_name": "John Doe",
            "beneficiary_account": "1172993826",
            "beneficiary_bank": "bni",
            "amount": 100000,
            "notes": "Payout April 17"
        }
    ]
}`

Also, you can download the Postman collection that covers the Iris API from this page
https://docs.midtrans.com/en/technical-reference/postman-collection?id=midtrans-iris-api-postman-collection

Any related general questions, you can reach out to us via email support@midtrans.com
Thank you

**Comment by richardreynaldo** [comment]
hi @Xaxxis I want to know if you do expect the difference in errors of the create and approve error response body is different? 
you can see that in the create payout error the errors would be
`"errors": {
        "0": [
            "Beneficiary name can't be blank",
            "Beneficiary name only allows space, alphanumeric, non-latin letter, non-latin numeric, \".\" and \",\" characters"
        ]
    }`
meanwhile in the approve payout error the errors would be
`"errors": [
        "Reference nos 'ce5u4cppr7fkehf45g' are not queued"
    ]`

**Comment by Xaxxis** [comment]
Hi @richardreynaldo yes this is expected, those APIs have a different error. On creating payout the error happened due to missing the `beneficiary_name` field

On the Approve  API, we can't find the reference number `ce5u4cppr7fkehf45g`. Makes sure you send the correct value reference number. However, if Iris didn't find the reference number,  it will reproduce the error message
`"errors": [ "Reference nos 'ce5u4cppr7fkehf45g' are not queued" ]`

**Comment by richardreynaldo** [comment]
@Xaxxis but why does the create payout errors have "0" inside the errors json meanwhile the approve payout doesn't have the "0" inside the json?

**Comment by richardreynaldo** [comment]
@Xaxxis and because of that the error we got on midtrans.error is this
`&{Message:Invalid body response, parse error during API request to Midtrans with message: json: cannot unmarshal object into Go struct field CreatePayoutResponse.errors of type []string StatusCode:400 RawError:json: cannot unmarshal object into Go struct field CreatePayoutResponse.errors of type []string RawApiResponse:0xc000656000}`

**Comment by rizdaprasetya** [comment]
I think you refers to the difference of `errors` JSON structure between that 2 API endpoints, in that case, yes it seems like a valid issue. And currently this Go module can't properly parse the errors `response` from `/payouts`. (Potential quick workaround is to change [this line](https://github.com/Midtrans/midtrans-go/blob/7889ad6bdcf9e7fd1f5565fd74f2e81e86f53099/iris/response.go#L32) to accept `interface{}` )

But for proper parsing, we'll need to check this with our Iris API team first, and get back to you sometimes around next week.
Thanks for reporting.

**Comment by richardreynaldo** [comment]
@rizdaprasetya ah sorry that's my point, my issues before maybe unclear. thanks a lot for the attention.

**Comment by rizdaprasetya** [comment]
Sorry late update, few days ago our Iris API team acknowledged the issue, which is a valid issue. They will check & try to improve it. Also the reason why create payout have index as key was because on payout creation, each payout can have more than 1 error.

We are waiting for the proper spec from them to update this Go module accordingly. Thanks!
As for now, the workaround is:
- handle the error with try-catch
- or potential manual workaround is to change this [line](https://github.com/Midtrans/midtrans-go/blob/7889ad6bdcf9e7fd1f5565fd74f2e81e86f53099/iris/response.go#L32) to accept `interface{}`

**Comment by Xaxxis** [comment]
Hi @richardreynaldo the issue has been solved on the [new version v1.2.2](https://github.com/Midtrans/midtrans-go/releases/tag/v1.2.2) ya

Thank you
